print("Welcome")
print("Your data is not stored in our server so, play fearlessly")
print("only one word anwers are allowed")
print("This game is in beta stage more questions and improvements will be added soon")
print("Type anything and tap enter to verify that you are are not a robot")
n0=input()
print("you entered",n0)
print("you are verified as a human enjoy the game by answering the questions")
print("AI: Hello,what's your name?")
n1=input()
print("AI: Where are you from?")
n2=input()
print("AI: What is your age?")
n3=input()
print("AI: Tell me your hobbies")
n4=input()
print("AI: Which outdoor game you like the most?")
n5=input()
print("Which indoor game is your favourite?")
n9=input()
print("Which is your favourite online game?")
n6=input()
print("Which is your favourite food?")
n7=input()
print("What you want to be in your life? if you are a grown up man please tell your job")
n8=input()
print("What your mother is?")
n10=input()
print("What you father is?")
n11=input()
print("So you are",n1)
print("You are from",n2)
print("You are of",n3)
print("Your hobbies are",n4)
print("Your favourite outdoor game is",n5)
print("Your favourite indoor game is",n9)
print("Your favourite online game is",n6)
print("Your favourite food is",n7)
print("You want to be or your job is",n8)
print("So your mother is",n10)
print("So your father is",n11)
print("Thanks for answering the questions and playing our game please rate our game so you can get more amazing games like this")
print("BYE BYE Meet you in the next game")